//! Vision — Flatbuffer frame parser and processor
//!
//! # Zero-copy pipeline
//! ```text
//! ipc::FrameBuffer (Arc<[u8]>)      — ZMQ bytes, ref-counted, no copy
//!     │
//!     ▼  flatbuffers::root::<Frame>()
//! Frame<'_>                          — zero-copy view into Arc bytes
//!     │
//!     ▼  frame.pixels().bytes()
//! &[u8]  pixel slice                 — direct pointer into flatbuffer
//!     │
//!     ▼  zerocopy::LayoutVerified::new_slice()
//! &[Pixel]                           — typed view, zero-copy cast
//! ```
//!
//! # Persona constraints enforced here
//! - No `.unwrap()` — every `Option`/`Result` maps to `FrameError`.
//! - No heap allocation during frame processing; `Arc` was allocated in ipc.
//! - `clippy::all` is denied — warnings are blockers.

#![deny(clippy::all)]
#![deny(clippy::unwrap_used)]
#![deny(clippy::expect_used)]

// Generated by flatc at build time — see build.rs.
// Contains: mod vision_ipc { pub struct Frame<'a> { … } }
#[allow(dead_code, unused_imports, clippy::all, clippy::unwrap_used)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/vision_frame_generated.rs"));
}

use generated::vision_ipc::root_as_frame;

use crossbeam_channel::Receiver;
use ipc::FrameBuffer;
use thiserror::Error;
use zerocopy::Ref;

// ── Pixel type ────────────────────────────────────────────────────────────────

/// RGB pixel — packed, no padding. zerocopy-safe for direct slice casting.
#[derive(Debug, Clone, Copy, zerocopy::AsBytes, zerocopy::FromZeroes, zerocopy::FromBytes)]
#[repr(C)]
pub struct Pixel {
    pub r: u8,
    pub g: u8,
    pub b: u8,
}

// ── Parsed frame view ─────────────────────────────────────────────────────────

/// Metadata extracted from a flatbuffer frame header (copied — 20 bytes).
/// Pixel data is NOT copied; access it via `FrameProcessor::with_pixels`.
#[derive(Debug, Clone, Copy)]
pub struct FrameMeta {
    pub timestamp_ns: u64,
    pub width:        u32,
    pub height:       u32,
    pub channels:     u8,
}

#[derive(Debug, Error)]
pub enum FrameError {
    #[error("flatbuffer verification failed")]
    InvalidFlatbuffer,
    #[error("pixels field missing in frame")]
    MissingPixels,
    #[error("pixel buffer length is not a multiple of size_of::<Pixel>()")]
    PixelAlignment,
    #[error("declared dimensions don't match pixel buffer length")]
    DimensionMismatch,
}

// ── Frame processor ───────────────────────────────────────────────────────────

pub struct FrameProcessor {
    rx: Receiver<FrameBuffer>,
}

impl FrameProcessor {
    pub fn new(rx: Receiver<FrameBuffer>) -> Self {
        Self { rx }
    }

    /// Block until a frame arrives, then call `f` with zero-copy pixel access.
    ///
    /// # Safety contract
    /// `f` must not retain a reference to `pixels` beyond its own scope.
    /// The `Arc<[u8]>` backing the pixels lives only for this call.
    pub fn process_next<F, T>(&self, f: F) -> Result<T, FrameError>
    where
        F: FnOnce(FrameMeta, &[Pixel]) -> T,
    {
        // Blocks until a frame is available or channel closes.
        // Unwrap here is the ONLY permitted one: channel closed = unrecoverable.
        let buf = self.rx.recv().map_err(|_| FrameError::InvalidFlatbuffer)?;

        self.parse_and_call(&buf, f)
    }

    fn parse_and_call<F, T>(&self, buf: &[u8], f: F) -> Result<T, FrameError>
    where
        F: FnOnce(FrameMeta, &[Pixel]) -> T,
    {
        // Zero-copy: creates a view into `buf` — no data is moved.
        let frame = root_as_frame(buf).map_err(|_| FrameError::InvalidFlatbuffer)?;

        let meta = FrameMeta {
            timestamp_ns: frame.timestamp_ns(),
            width:        frame.width(),
            height:       frame.height(),
            channels:     frame.channels(),
        };

        // flatbuffers 2.0: pixels() on a [uint8] field returns Option<&[u8]> directly.
        let pixel_bytes: &[u8] = frame
            .pixels()
            .ok_or(FrameError::MissingPixels)?;

        // Guard: declared dimensions must match actual byte count.
        let expected = meta.width as usize
            * meta.height as usize
            * meta.channels as usize;
        if pixel_bytes.len() != expected {
            return Err(FrameError::DimensionMismatch);
        }

        // zerocopy cast: &[u8] → &[Pixel], zero-copy, alignment-checked.
        let pixels: &[Pixel] = Ref::<_, [Pixel]>::new_slice(pixel_bytes)
            .ok_or(FrameError::PixelAlignment)?
            .into_slice();

        Ok(f(meta, pixels))
    }
}
